### ISSUE TITLE
Create pressure-sensitive lighting mode

### ISSUE THREAD

**Issue by zachgoldstein** [zachgoldstein/heavy-meta-lights#17]
## How would this work?

- A softly glowing lighting effect continuously runs
- When a pressure spike is detected from the bmp280 sensor (ala fireball), 
- All lights would ramp up to some brightness/ color and then fall back to the original effect
  - The brightness would be scaled by the spike magnitude
- Scale brightness of light based on lta - sta magnitude

## What's done:
- We hooked up a bmp280 sensor to the raspi and could pull pressure/temp readings
- We wrote a simple LTA/STA snippet that could detect pretty faint pressure changes
- There is code for soft background lights in the lifx samples that we can pull in.

## Todos
- [ ] Write a new lighting mode that will react to pressure spikes
- [ ] Pull in code snippet that runs soft background lighting and combine with pressure spikes
- [ ] Setup a way for us to customise the sensitivity for the smallest detection via the UI
- [ ] Find the max magnitude pressure change that occurs when shooting fire

## Nice-to-haves that probably won't happen:
- Set brightness on specific light groups
